apiVersion: 1

datasources:
  - name: grafana-postgresql-datasource
    type: postgres
    access: proxy
    url: db:5432
    user: tower
    secureJsonData:
      password: towerpass
    jsonData:
      database: towerdb
      sslmode: disable
    isDefault: true